#!/usr/bin/env python3
"""Generate a security clearance certificate in Markdown format."""

import argparse
import subprocess
import sys
from datetime import date
from pathlib import Path


def git_hash(project_path: Path) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(project_path), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True
        )
        return result.stdout.strip()
    except Exception:
        return "n/a"


def main():
    parser = argparse.ArgumentParser(description="Generate a local security audit certificate")
    parser.add_argument("--project", required=True, help="Project name or path")
    parser.add_argument("--findings", required=True,
                        help='Findings summary, e.g. "0 Critical, 0 High, 2 Medium, 1 Low, 3 Info"')
    parser.add_argument("--output", default="~/Desktop",
                        help="Output directory (default: ~/Desktop)")
    parser.add_argument("--auditor", default="Claude Code (local-audit skill v1)",
                        help="Auditor name to appear on certificate")
    args = parser.parse_args()

    output_dir = Path(args.output).expanduser()
    output_dir.mkdir(parents=True, exist_ok=True)

    today = date.today()
    date_str = today.strftime("%Y-%m-%d")
    date_long = today.strftime("%B %d, %Y")

    project_path = Path(args.project).expanduser().resolve()
    commit_ref = git_hash(project_path) if project_path.exists() else "n/a"

    # Determine overall rating from findings string
    findings_lower = args.findings.lower()
    if "critical" in findings_lower and not findings_lower.startswith("0 critical"):
        overall = "CONDITIONAL — Critical issues remain"
        badge = "⚠️  CONDITIONAL"
    elif "high" in findings_lower and not findings_lower.startswith("0 high"):
        overall = "CONDITIONAL — High-severity issues remain"
        badge = "⚠️  CONDITIONAL"
    else:
        overall = "CLEAN"
        badge = "✅  CLEAN"

    cert = f"""# Security Audit Certificate

```
╔══════════════════════════════════════════════════════════╗
║          LOCAL SECURITY AUDIT CERTIFICATE                ║
║                                                          ║
║  Status : {badge:<46} ║
║  Project: {args.project:<46} ║
║  Date   : {date_long:<46} ║
║  Ref    : {commit_ref:<46} ║
╚══════════════════════════════════════════════════════════╝
```

## Audit Summary

| Field | Value |
|-------|-------|
| **Project** | `{args.project}` |
| **Audit date** | {date_long} |
| **Audited by** | {args.auditor} |
| **Git commit** | `{commit_ref}` |
| **Overall status** | **{overall}** |

## Findings Breakdown

{args.findings}

## Audit Scope

- Phase 1: Secrets & credentials scan (git history + working tree)
- Phase 2: Static code analysis (SAST) — semgrep, bandit, pattern grep
- Phase 3: Dependency vulnerability audit — pip-audit / npm audit / osv-scanner
- Phase 4: Claude Code config & plugin audit

## Conditions

This certificate confirms that the above project was audited on {date_long} by the
Claude Code **local-audit** skill and the findings listed above were the complete
results at that point in time.

This certificate is valid for **30 days** from the audit date or until the next
significant commit, whichever comes first. Re-run the audit before major releases.

---

*Generated by Claude Code local-audit skill — https://github.com/joao-silva/security-audit-skill*
"""

    out_file = output_dir / f"security-certificate-{date_str}.md"
    out_file.write_text(cert, encoding="utf-8")
    print(f"Certificate written to: {out_file}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
